# -*- coding: utf-8 -*-
"""potenciaRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class Potenciador:
    def __init__(self, base, exponente):
        """
        Inicializa la clase con la base y el exponente.

        :param base: Número base (a)
        :param exponente: Exponente (b)
        """
        self.base = base
        self.exponente = exponente

    def calcular(self):
        """
        Método público que inicia el cálculo de la potencia.

        :return: Resultado de base elevado a exponente
        """
        return self._potencia_recursiva(self.base, self.exponente)

    def _potencia_recursiva(self, a, b):
        """
        Método recursivo privado que calcula a^b.

        :param a: base
        :param b: exponente
        :return: a elevado a b
        """
        if b == 0:
            return 1
        else:
            return a * self._potencia_recursiva(a, b - 1)


# Ejemplo de uso:
pot = Potenciador(2, 3)
print(pot.calcular())  # Salida esperada: 8